---
    title: "Global ETF Map"
resource_files:
    - etfData.RDat
runtime: shiny
output:
    flexdashboard::flex_dashboard:
    source_code: embed
---
    
    
    ```{r setup, include=FALSE}
# Load packages.

library(flexdashboard)
library(dygraphs)
library(leaflet)
library(quantmod)
library(dplyr)
library(dplyr)

# Load data here.  Remember, we saved the map and ETF data in the shapefile when we 
# imported, tidied and built them in the Notebook.

load('etfData.RDat')

# The next lines are taken straight from the Notebook. We just need
# to rebuild that map.

ytdPal <- colorQuantile("Blues", world_etf$ytd, n = 20)

ytdPopup <- paste0("Country: ", 
                   world_etf$name,
                   " Year-to-date: ", 
                   world_etf$ytd, "%")


leaf_world_etf <- leaflet(world_etf) %>%
    addProviderTiles("CartoDB.Positron") %>% 
    setView(lng =  20, lat =  15, zoom = 2) %>%
    addPolygons(stroke = FALSE, smoothFactor = 0.2, fillOpacity = .7,
                
                # The next line of code is really important!       
                
                color =~ytdPal(ytd), layerId = ~ticker, popup = ytdPopup)

```

World Map Selector {data-orientation=rows}
=====================================
    
    Row {data-height=650}
-------------------------------------
    
    ### World Map
    
    ```{r, echo = FALSE}
leafletOutput("map1")

output$map1 <- renderLeaflet({
    leaf_world_etf
})
```

Row {data-height=350}
-------------------------------------
    
    ### Country ETF
    
    ```{r, echo = FALSE}

dygraphOutput("dygraph")

# A reactive that captures the name of the country clicked. 
# Note that it captures the id of the shape that was clicked, 
# when we built our leaflet map in the DataGrab Notebook 
# we prepared for this and assigned 'layerId = ticker' so we could capture
# the ticker upon click of a country.

clickedCountry <- eventReactive(input$map1_shape_click, {
    return(input$map1_shape_click$id)
})

output$dygraph <- renderDygraph({
    validate(need(clickedCountry(), "There is no iShares ETF for that country"))
    
    etf <- getSymbols(as.character(clickedCountry()), auto.assign = FALSE)
    
    dygraph(Cl(etf), main = clickedCountry())  %>%
        
        # A range selector comes in handy for zooming to the start date for each ETF.
        
        dyRangeSelector(height = 20) %>%
        
        ##add shading for the recession from December 2012 to June 2009
        
        dyShading(from = "2007-12-01", to = "2009-06-01", color = "#FFE6E6") %>% 
        
        # Add a line for an important economic event - how about the Brexit vote? 
        
        dyEvent(x = "2016-06-23", label = "Brexit Vote", labelLoc = "top", color = "red")
    
})

```



